## 1. Basics of NumPy

### 1.1 NumPy Package

In [32]:
import numpy as np

### 1.2 Advantages
Arrays are one of the core data structures of the NumPy library, essential for organizing data. We can think of them as a grid of values, all of the same type. Python lists are limited in functions and take up more space and time to process than NumPy arrays.

NumPy provides an array object that is much faster and more compact than Python lists. Through its extensive API integration, the library offers many built-in functions that make computing much easier with only a few lines of code. This can be a huge advantage when performing math operations on large datasets. 

The array object in NumPy is called `ndarray` meaning 'n-dimensional array'. To begin with, we will use one of the most common array types: the one-dimensional array ('1-D'). A 1-D array represents a standard list of values entirely in one dimension. Remember that in NumPy, all of the elements within the array are of the same type.

In [33]:
one_dimensional_arr = np.array([10, 12])
print(one_dimensional_arr)

[10 12]


### 1.3 Creating NumPy Arrays

In [34]:
# Create and print a NumPy array 'a' containing the elements 1, 2, 3.
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [35]:
# Create an array with 3 integers, starting from the default integer 0.
b = np.arange(3)
print(b)

[0 1 2]


In [36]:
# Create an array that starts from the integer 1, ends at 20, incremented by 3.
c = np.arange(1, 20, 3)
print(c)
print(c.dtype)

[ 1  4  7 10 13 16 19]
int64


In [37]:
# Creating evenly spaced arrays
lin_spaced_arr = np.linspace(0, 100, 5)
print(lin_spaced_arr)
print(lin_spaced_arr.dtype)

[  0.  25.  50.  75. 100.]
float64


In [38]:
# Creating arrays by specifying the datatype
lin_spaced_arr_int = np.linspace(0, 100, 5, dtype=np.int64)
print(lin_spaced_arr_int)
print(lin_spaced_arr_int.dtype)

[  0  25  50  75 100]
int64


In [39]:
c_float = np.arange(0, 100, 2, dtype=np.float64)
print(c_float)
print(c_float.dtype)

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32. 34.
 36. 38. 40. 42. 44. 46. 48. 50. 52. 54. 56. 58. 60. 62. 64. 66. 68. 70.
 72. 74. 76. 78. 80. 82. 84. 86. 88. 90. 92. 94. 96. 98.]
float64


In [40]:
char_arr = np.array(['Hello, World!'], dtype='<U5')
print(char_arr)
print(char_arr.dtype)

['Hello']
<U5


### 1.4 More on Arrays

In [41]:
# Return a new array of shape 3, filled with ones. 
ones_arr = np.ones(3)
print(ones_arr)

[1. 1. 1.]


In [42]:
# Return a new array of shape 3, filled with zeroes.
zeros_arr = np.zeros(3)
print(zeros_arr)

[0. 0. 0.]


In [43]:
# Return a new array of shape 3, without initializing entries.
empt_arr = np.empty(3)
print(empt_arr)

[0. 0. 0.]


In [44]:
# Return a new array of shape 3 with random numbers between 0 and 1.
rand_arr = np.random.rand(3)
print(rand_arr)

[0.72433319 0.00634375 0.427569  ]


## 2. Multidimensional Arrays

In [55]:
# Create a 2 dimensional array (2-D)
two_dim_arr = np.array([[1, 2, 3],
                      [4, 5, 6]])
print(two_dim_arr)
print(f"Shape: {two_dim_arr.shape}")
print(f"Size: {two_dim_arr.size}")
print(f"Dimension: {two_dim_arr.ndim}")

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size: 6
Dimension: 2


In [56]:
# Reshaping Array
one_dim_arr = np.array([501, 502, 503, 505, 506, 507, 508, 509, 510, 511, 512, 513])
two_dim_arr = np.reshape(one_dim_arr, (4, 3))
print(two_dim_arr)
print(f"Shape: {two_dim_arr.shape}")
print(f"Size: {two_dim_arr.size}")
print(f"Dimension: {two_dim_arr.ndim}")

[[501 502 503]
 [505 506 507]
 [508 509 510]
 [511 512 513]]
Shape: (4, 3)
Size: 12
Dimension: 2


## 3. Array Math Operations

In [63]:
arr_1 = np.random.randint(501, 552, (4, 3), dtype=np.int64)
arr_2 = np.random.randint(907, 987, (4, 3), dtype=np.int64)
print(arr_1 + arr_2)
print(arr_1 - arr_2)
print(arr_1 * arr_2)
print(arr_2 / arr_1)
print(arr_2 // arr_1)
print(arr_2 % arr_1)

[[1420 1492 1446]
 [1468 1490 1439]
 [1510 1424 1481]
 [1518 1497 1479]]
[[-396 -426 -374]
 [-460 -474 -423]
 [-430 -402 -469]
 [-434 -457 -427]]
[[464896 511147 487760]
 [485856 498856 472948]
 [523800 466543 493350]
 [528992 508040 501278]]
[[1.7734375  1.79924953 1.69776119]
 [1.91269841 1.93307087 1.83267717]
 [1.7962963  1.78669276 1.92687747]
 [1.80073801 1.87884615 1.81178707]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
[[396 426 374]
 [460 474 423]
 [430 402 469]
 [434 457 427]]


### 3.1 - Multiplying vector with a scalar (broadcasting)

In [65]:
vector = np.array([1, 3, 6])
scalar = 4.2
print(scalar * vector)

[ 4.2 12.6 25.2]


## 4. Indexing & Slicing

### 4-1 Indexing

In [68]:
# Select the third element of the array. Remember the counting starts from 0.
a = np.array([1, 2, 3, 4, 5])
print(a[2])

# Select the first element of the array.
print(a[0])

3
1


For multidimensional arrays of shape `n`, to index a specific element, we must input `n` indices, one for each dimension. There are two common ways to do this, either by using two sets of brackets, or by using a single bracket and separating each index by a comma.

In [69]:
# Indexing on a 2-D array
two_dim = np.array(([1, 2, 3],
          [4, 5, 6], 
          [7, 8, 9]))

In [70]:
# Select element number 8 from the 2-D array using indices i, j and two sets of brackets
print(two_dim[2][1])

8


In [71]:
# Select element number 8 from the 2-D array, this time using i and j indexes in a single 
# set of brackets, separated by a comma
print(two_dim[2, 1])

8


### 4-2 Slicing

In [72]:
# Slice the array a to get the array [2,3,4]
sliced_arr = a[1:4]
print(sliced_arr)

[2 3 4]


In [73]:
# Slice the array a to get the array [1,2,3]
sliced_arr = a[:3]
print(sliced_arr)

[1 2 3]


In [74]:
# Slice the array a to get the array [3,4,5]
sliced_arr = a[2:]
print(sliced_arr)

[3 4 5]


In [76]:
# Slice the array a to get the array [1,3,5]
sliced_arr = a[::2]
print(sliced_arr)

[1 3 5]


In [78]:
# Note that a == a[:] == a[::]
print(a == a[:])
print(a == a[::])

[ True  True  True  True  True]
[ True  True  True  True  True]


In [82]:
# Slice the two_dim array to get the first two rows
sliced_arr = two_dim[0:2]
print(sliced_arr)

[[1 2 3]
 [4 5 6]]


In [84]:
# Similarily, slice the two_dim array to get the last two rows
sliced_arr = two_dim[1:3]
print(sliced_arr)

[[4 5 6]
 [7 8 9]]


In [86]:
# Slicing Columns
sliced_arr = two_dim[:, 0] # first column
print(sliced_arr)

[1 4 7]


In [88]:
sliced_arr = two_dim[:, 2] # last column
print(sliced_arr)

[3 6 9]


In [89]:
sliced_arr = two_dim[1:3, 0:2] # first two columns from last two rows
print(sliced_arr)

[[4 5]
 [7 8]]


## 5. Stacking & Splitting

In [106]:
a1 = np.array([[1,1], 
               [2,2]])
a2 = np.array([[3,3],
              [4,4]])
print(f'a1:\n{a1}')
print(f'a2:\n{a2}')

a1:
[[1 1]
 [2 2]]
a2:
[[3 3]
 [4 4]]


In [107]:
# Stacking arrays vertically
vert_stack = np.vstack((a1, a2))
print(vert_stack)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [108]:
# Stacking arrays horizontally
horz_stack = np.hstack((a1, a2))
print(horz_stack)

[[1 1 3 3]
 [2 2 4 4]]


In [109]:
# Split the horizontally stacked array into 2 separate arrays of equal size
horz_split_two = np.hsplit(horz_stack, 2)
print(horz_split_two)

[array([[1, 1],
       [2, 2]]), array([[3, 3],
       [4, 4]])]


In [110]:
# Splitting after certain column
horz_split_first = np.hsplit(horz_stack, [1]) # splitting after first column
print(horz_split_first)

[array([[1],
       [2]]), array([[1, 3, 3],
       [2, 4, 4]])]


In [111]:
# Split the vertically stacked array into 2 separate arrays of equal size
vert_split_two = np.vsplit(vert_stack,2)
print(vert_split_two)

[array([[1, 1],
       [2, 2]]), array([[3, 3],
       [4, 4]])]


In [112]:
# Split the vertically stacked array after the first and third row
vert_split_first_third = np.vsplit(vert_stack,[1, 3])
print(vert_split_first_third)

[array([[1, 1]]), array([[2, 2],
       [3, 3]]), array([[4, 4]])]
