In [1]:
import numpy as np

## 1 - Representing and Solving a System of Linear Equations using Matrices

### 1.1 - System of Linear Equations

Here is a **system of linear equations** (or **linear system**) with three equations and three unknown variables:


$$\begin{cases} 
4x_1-3x_2+x_3=-10, \\ 2x_1+x_2+3x_3=0, \\ -x_1+2x_2-5x_3=17, \end{cases}\tag{1}$$

**To solve** this system of linear equations means to find such values of the variables $x_1$, $x_2$, $x_3$, that all of its equations are simultaneously satisfied.

### 1.2 - Solving Systems of Linear Equations using Matrices

Let's prepare to solve the linear system $(1)$ using `NumPy`. $A$ will be a matrix, each row will represent one equation in the system and each column will correspond to the variable $x_1$, $x_2$, $x_3$. And $b$ is a 1-D array of the free (right side) coefficients:

In [3]:
A = np.array([
    [4, -3, 1],
    [2, 1, 3],
    [-1, 2, -5]
])
b = np.array([-10, 0, 17])
print("Matrix A:")
print(A)
print("Vector b:")
print(b)

Matrix A:
[[ 4 -3  1]
 [ 2  1  3]
 [-1  2 -5]]
Vector b:
[-10   0  17]


In [4]:
print(f"Shape of A: {np.shape(A)}")
print(f"Shape of b: {np.shape(b)}")

Shape of A: (3, 3)
Shape of b: (3,)


In [5]:
x = np.linalg.solve(A, b)
print(f"Solution: {x}")

Solution: [ 1.  4. -2.]


In [6]:
d = np.linalg.det(A)
print(f"Determinant of matrix A: {d:.2f}")

Determinant of matrix A: -60.00


### 1.3 - What happens if the system has no unique solution?

Let's explore what happens if we use `np.linalg.solve` in a system with no unique solution (no solution at all or infinitely many solutions).

Given another system of linear equations:

$$\begin{cases} 
x_1+x_2+x_3=2, \\ x_2-3x_3=1, \\ 2x_1+x_2+5x_3=0, \end{cases}\tag{2}$$

let's find the determinant of the corresponding matrix.

In [7]:
A_2= np.array([
        [1, 1, 1],
        [0, 1, -3],
        [2, 1, 5]
    ], dtype=np.dtype(float))

b_2 = np.array([2, 1, 0], dtype=np.dtype(float))

print(np.linalg.solve(A_2, b_2))

LinAlgError: Singular matrix

it throws a `LinAlgError` because the matrix is singular.

In [15]:
d_2 = np.linalg.det(A_2)

print(f"Determinant of matrix A_2: {d_2:.2f}")

Determinant of matrix A_2: 0.00


In [16]:
try:
    solution = np.linalg.solve(A_2, b_2)
    print(solution)
except np.linalg.LinAlgError as e:
    print(e)

Singular matrix
